spring:
  application:
    name: activityservices
  data:
    mongodb:
      uri: mongodb+srv://rajeevranjan9560807144:ofvHncQbFvTYY0Bb@cluster0.slnibwd.mongodb.net/fitness?retryWrites=true&w=majority&appName=Cluster0


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
    registerWithEureka: true   # Register this client with Eureka Server
    fetchRegistry: true        # Fetch the registry to know other services

server:
  port: 8082
