spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb+srv://rajeevranjan9560807144:ofvHncQbFvTYY0Bb@cluster0.slnibwd.mongodb.net/aiservice?retryWrites=true&w=majority&appName=Cluster0


  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: activity-processor-group
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.header: false
        spring.json.value.default.type : com.fitness.aiservice.model.Activity

    topic:
      name: activity-events

gemini:
  api:
    key: ${GEMINI_KEY}
    url: ${GEMINI_URL}




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
    registerWithEureka: true   # Register this client with Eureka Server
    fetchRegistry: true        # Fetch the registry to know other services

server:
  port: 8085