spring:
  datasource:
    url: jdbc:postgresql://ep-lingering-cherry-ad3xf1zf-pooler.c-2.us-east-1.aws.neon.tech/fitness?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_NkPF4xCphA1Q
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 8081
